config/routes.rb
Rails.application.routes.draw do
  get "hadouken", to: "commands#hadouken"
  get "/214214P", to: "commands#214214P", as: :command_214214P
  get "ikkaiten", to: "commands#ikkaiten"
  root to: 'homes#index'
  resources :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  def show
    render params[:page]
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/commands/214214P.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
</head>
<body>
  
  <h1>214214Pコマンド練習</h1>
  <p>↓ ↙ ← ↓ ↙ ← + P を20フレーム以内に入力してください</p>
  <p>キーボード：WASD（方向） / U・J（パンチ）</p>
  <div id="log">キーボードまたはコントローラーで入力してください。</div>
  <div id="history"></div>

  <script src="P214214.js"></script>

</body>
</html>

app/views/commands/hadouken.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
</head>
<body>
  
  <h1>真空波動拳コマンド練習</h1>
  <p>↓ ↘ → ↓ ↘ → + P を20フレーム以内に入力してください</p>
  <p>キーボード：WASD（方向） / U・J（パンチ）</p>
  <div id="log">キーボードまたはコントローラーで入力してください。</div>
  <div id="history"></div>

  <script src="main.js"></script>

</body>
</html>

app/views/commands/ikkaiten.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
</head>
<body>
  
  <h1>一回転コマンド練習</h1>
  <p>↓ ↘ → ↓ ↘ → + P を20フレーム以内に入力してください</p>
  <p>キーボード：WASD（方向） / U・J（パンチ）</p>
  <div id="log">キーボードまたはコントローラーで入力してください。</div>
  <div id="history"></div>

  <script src="ikkaiten.js"></script>

</body>
</html>

app/views/homes/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
</head>
<body>
  <h1>コマンド・コンボ練習サイト</h1>
  <p>キーボード/コントローラー両対応です</p>
  <div id="log">以下から練習するコマンド・コンボを選択してください</div>
  <%= link_to "236236Pコマンド", hadouken_path %><br>
  <%= link_to "214214Pコマンド", command_214214P_path %><br>
  <%= link_to "一回転コマンド", ikkaiten_path%>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practicecom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>